### ISSUE TITLE
Add `npmlog` to package.json?

### ISSUE THREAD

**Issue by adamvert** [eHealthAfrica/kazana-config#46]
Given that there seems to be a bug in npm that causes this error:

```
app_1 | Error: Cannot find module 'npmlog'
app_1 |     at Function.Module._resolveFilename (module.js:337:15)
app_1 |     at Function.Module._load (module.js:287:25)
app_1 |     at Module.require (module.js:366:17)
app_1 |     at require (module.js:385:17)
app_1 |     at Object.<anonymous> (/code/van/node_modules/kazana-config/index.js:4:11)
app_1 |     at Module._compile (module.js:435:26)
app_1 |     at Object.Module._extensions..js (module.js:442:10)
app_1 |     at Module.load (module.js:356:32)
app_1 |     at Function.Module._load (module.js:311:12)
app_1 |     at Module.require (module.js:366:17)
app_1 |     at require (module.js:385:17)
```

Would it be possible/sensible to explicitly add `npmlog` to `package.json`?

**Comment by gr2m** [comment]
wow that’s a classic "I have no idea how this could ever work" :/ I'm on it

**Comment by gr2m** [comment]
released as https://github.com/eHealthAfrica/kazana-config/releases/tag/v5.4.3
